export const icons = {
  play: { ios: 'play.fill', android: 'play_arrow' },
  pause: { ios: 'pause.fill', android: 'pause' },
  stop: { ios: 'stop.fill', android: 'stop' },
  next: { ios: 'forward.fill', android: 'skip_next' },
  previous: { ios: 'backward.fill', android: 'skip_previous' },
  heart: { ios: 'heart', android: 'favorite' },
  heartFill: { ios: 'heart.fill', android: 'favorite' },
  moon: { ios: 'moon.zzz', android: 'bedtime' },
  moonFill: { ios: 'moon.zzz.fill', android: 'bedtime' },
  share: { ios: 'square.and.arrow.up', android: 'share' },
  chevronDown: { ios: 'chevron.down', android: 'keyboard_arrow_down' },
  chevronRight: { ios: 'chevron.right', android: 'chevron_right' },
  close: { ios: 'xmark', android: 'close' },
  search: { ios: 'magnifyingglass', android: 'search' },
  globe: { ios: 'globe.europe.africa.fill', android: 'public' },
  map: { ios: 'map', android: 'map' },
  more: { ios: 'ellipsis', android: 'more_horiz' },
  info: { ios: 'info.circle', android: 'info' },
  link: { ios: 'safari', android: 'open_in_browser' },
  copy: { ios: 'doc.on.doc', android: 'content_copy' },
  music: { ios: 'music.note', android: 'music_note' },
  musicList: { ios: 'music.note.list', android: 'queue_music' },
  clock: { ios: 'clock.arrow.circlepath', android: 'history' },
  radio: { ios: 'dot.radiowaves.left.and.right', android: 'radio' },
  antenna: { ios: 'antenna.radiowaves.left.and.right', android: 'cell_tower' },
  trash: { ios: 'trash', android: 'delete' },
  star: { ios: 'star.fill', android: 'star' },
  mail: { ios: 'envelope', android: 'mail' },
  hand: { ios: 'hand.raised', android: 'privacy_tip' },
  doc: { ios: 'doc.text', android: 'description' },
  sparkles: { ios: 'sparkles', android: 'auto_awesome' },
  plus: { ios: 'plus', android: 'add' },
  language: { ios: 'character.bubble', android: 'translate' },
  paint: { ios: 'circle.lefthalf.filled', android: 'contrast' },
  location: { ios: 'location', android: 'location_on' },
  flag: { ios: 'flag', android: 'flag' },
  waveform: { ios: 'waveform', android: 'graphic_eq' },
  wifiOff: { ios: 'wifi.slash', android: 'wifi_off' },
  warning: { ios: 'exclamationmark.triangle.fill', android: 'warning' },
  refresh: { ios: 'arrow.clockwise', android: 'refresh' },
  reorder: { ios: 'line.3.horizontal', android: 'drag_handle' },
  minus: { ios: 'minus.circle.fill', android: 'remove_circle' },
  check: { ios: 'checkmark', android: 'check' },
  heartText: { ios: 'heart.text.square', android: 'favorite' },
} as const;

export type IconName = keyof typeof icons;

export const filledOnAndroid: Partial<Record<IconName, boolean>> = {
  heartFill: true,
  play: true,
  pause: true,
  next: true,
  previous: true,
  moonFill: true,
  star: true,
  globe: true,
  minus: true,
  warning: true,
};
